et_platform_homepage:
    path:     /
    defaults: { _controller: ETPlatformBundle:Default:index }


et_platform_products_get:
    resource: ETPlatformBundle:Default
    type:     rest
    options:
        expose: true
        prefix: api

et_platform_product:
    resource: ETPlatformBundle:Product
    prefix: /product
    type:     rest
    options:
        expose: true
        prefix: api

et_platform_business:
    resource: ETPlatformBundle:Business
    prefix: /business
    type:     rest
    options:
        expose: true
        prefix: api

et_platform_user:
    resource: ETPlatformBundle:User
    prefix: /user
    type:     rest
    options:
        expose: true
        prefix: api
