<?php

namespace ET\PlatformBundle\Repository;


/**
 * BusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNumberBusiness()
    {
        $q = $this->createQueryBuilder('p')
            ->select('COUNT(p)');
        return $q->getQuery()->getSingleScalarResult();
    }

}
