<?php

namespace ET\PlatformBundle\Repository;

use ET\PlatformBundle\Entity\Business;

/**
 * BusinessProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductsFromBusiness(Business $business) {
        $qb = $this
            ->createQueryBuilder('a')
            ->addSelect('p')
            ->innerJoin('a.business', 'b')
            ->innerJoin('a.product', 'p')
            ->where('a.business = :business')
            ->setParameter('business', $business)
            ->getQuery()
        ;

        return $qb
            ->getResult()
            ;
    }
}
