<?php

namespace ET\PlatformBundle\Repository;


/**
 * BusinessProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findFreeProduct() {
        $qb = $this
            ->createQueryBuilder('p')
            ->addSelect('p')
            ->where('p.quantity_real > 0')
            ->getQuery();

        return $qb
            ->getResult()
            ;
    }
}
